language: java
dist: precise
jdk:
- oraclejdk8
script: sh gradlew build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "XGRV3FN4mpi5BlxaD+A4waaKwcb/WDyrgN3ynV72fhC3AKjeghmy4vhJlz7GddNyjQ0mTxqt3JMzJ2OCfSeaa6uTJrHiBRku3JnCuhMhbcA1G9YdtzUCpjyUECFrHQSPLFCIzXjuTEEJyBtWwY/bEVJo/Geh4i6E6gMYbuwlDLhbtppCR1K69AsQSolDQ0QJWZhiBX3w4aUT3/p7u/hb+G6LuNKcvvYh8LdWSnIuzxl6tv61EHeljmtoSizoIZDYcYk6Zm9YOmDjCkDRk1HGXmX026RHiuNqW5vqSH563qUwHqnu+43YDMc69m5H3gNQQjzWw6h3/knMD1dwv/+XfD5Znt6xxw7iR24FwwsFnBm+dt/iGB/Xr3hT5mpjyxJgDGijPuoNCGdWWKd1UL/U+VsMU1krPyH1R8dvT73EObnBPOqwLSjq0JoUXJq7oO8gbopLUXtSqzy7tunIhfpOMKMA1VX7QEs+YJuOUYTDJZWdYdCrpWAQDz10W8rBTksY1pJyZgD/D/yx1M7i+xSQ+ntj8kazfJ+9dHGAghv9B89HV3xKd2XzLl+2Xtoa6yxo84kn8Zb6E7bZ0DCbcVRtr4Myof7KGQLTd5X2YvMNeoSUFO071oZbbtvBxEbAs7u3fsQvRtkQKvqDkErmIBvtgm9WcTSmK1fsNoQTn6sFnqE="
  file: "/skybot-[0-9.]{3,}.jar$/"
  on:
    tags: true
