language: java
dist: precise
jdk:
- oraclejdk8
script: sh gradlew build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: a0MFnxh0c9O8hV6LEK+iDDPVuFRUUXwhrpZaPq6qcD+kq/CTjCz+wCUhR7cm6FK9lI0VShxDaQjVsrSOlTL/fEZKszhGwStWV5uG10AOG/B4A6VX1NsCGCocvt3RKZtoZN4uyWBL7LjY9Vca6Hl1x6/7y+wOsg/4HPghmJk3Bhda8pPUHEzOYXoTITgY220jbP6wNLyiex/GKYHiFY6XBfMIfw6K9yWriQ/DUDlRX40POM/6TC4bXhxaKjjFC/x5HiFUFRzpvpE34utLL6wGTUVruJblTk14YMlwlRzp4ReQYzCHUN/LAOWLjXp/nTbtnXBkutV8cA1a4QJWgEiGlgRrrmmdlKIiK7KfuvqOcy3LmRSASkAjTO5uY0vc6DbqV1caXslGYRawSWmg4bOFoVqWAY89+gWHLFCFI30OIPX5uleyXwdS0x4m3jA8dPT7Im4CSJ5EYoicqOrYh3hCTjyxL6mSyqdfSjFIhtfLwT42Cbb/OnXX1VrN9f0zT56FlXFtAqJKhHKcSYQOWYqpLyp17F7J4S2fHZPtj9Ax1roCYiTRoBXI5QgBp2yz+ELqgrPwTsuBi5O8hGcMcpFfLFOQNMXkO/RDM5tqIxKNSZkXimky/f/xwSWpNSsr7ASG80fKC/RcT0gZActJjucIU01IFz+eS2QuKNPbXTWX9f8=
  file:
    - skybot-3.50.3.jar
    - skybot-3.50.3-all.jar
  on:
    tags: true
