language: java
dist: precise
jdk:
- oraclejdk8
script: sh gradlew build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dgN/9oThB+chdt48Zg8WF7JqHe86k3Q50R6huY1B0vCKQiSBdQtI6RQioTb5qDxDQYDsFTC0IOYfyjBbTWas0/2tgnE0svgpdZQgqv9UYpKO3jCZfRaFm7MmWDWplyJiUr0oObYHGSvQkwInEcP6YlTli8skr/2In8PjM7XNUdzOzUSPA38Wb6k8VIWbwpKXSrowdtUJ2BfS8Dsp3SwiHN21n6hzcBHPsBCufztSPbsEDpX1c64YE2oihqin3QEAkxYrbi7XKp0VfMfUDwO+DIzdcOwZx8XJoaLcJz6plWlW/DRzlcdgHWxNH5H1yJC38H1PL1t6KMAEOT7AqcjHv5luKtQdIGtyw3YF5Ig4iGsM8/NIHNiNE2rwzFBrFFH7FqsEw66nYVDhxshiyphAvcgoIo3HRR0HO1d8PlSyjp9V3stuJ2jpj1A2jD+LXJH2Qm5mr5ONvEQe1ZCljPoXC2y7r8aOJumEOurCx9W1RpkRbUQXAd2ytgtYIO3V0RfE5RWo5rsWJXpkad+ptB2EhwbJ9A3JsurHHYZyP4H2JucHp/H/fhezhdvOORc0lQF50pvjmwpwYBK8iiYW4XM6ZpkNPHDt2EOdalIQrxdN+SwCAr/Ij565oYIf9NEkw9jbvW8s25d6AxYLT9hVxjOcwuotB8VS1pkF1aICO5avf3w=
  file:
    - /skybot-[0-9.]{3,}.jar$/
  on:
    tags: true
